version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: papXiv
      MYSQL_DATABASE: papXiv
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
