// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// PaperCreate defines model for PaperCreate.
type PaperCreate struct {
	Id        string `json:"id"`
	Published string `json:"published"`
	Subject   string `json:"subject"`
	Tag       string `json:"tag"`
	Title     string `json:"title"`
	Url       string `json:"url"`
}

// PaperGet defines model for PaperGet.
type PaperGet struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Published string `json:"published"`
	Subject   string `json:"subject"`
	Tag       string `json:"tag"`
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	Url       string `json:"url"`
}

// PaperList defines model for PaperList.
type PaperList struct {
	HasNext bool         `json:"has_next"`
	Papers  *[]PaperItem `json:"papers,omitempty"`
	Total   int          `json:"total"`
}

// ProblemDetail エラー表現として、 [Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) を用いる。
// API クライアントでのエラーハンドリングの実装時は、 `type` を利用する。
// リソース個別のエラー表現は、各API仕様に記載する。
type ProblemDetail struct {
	// Detail 個別の Problem を説明するヒューマンリーダブルな文章。
	// 通常、サーバーのエラー文を返す。
	Detail string `json:"detail"`

	// ErrorCode Title のスネークケース表現。Extension Member.
	ErrorCode string `json:"error_code"`

	// Instance エラー発生箇所を示す URI 表現 (リクエストを処理したエンドポイントのURI)
	Instance string `json:"instance"`

	// Status HTTP ステータスコード
	Status int `json:"status"`

	// Title Problem の `type` に対するヒューマンリーダブルな説明文
	Title string `json:"title"`

	// Type Problem の種別を一意に表現するURI
	Type string `json:"type"`
}

// SearchPaper defines model for SearchPaper.
type SearchPaper struct {
	Papers *[]struct {
		Title *string `json:"title,omitempty"`
		Url   *string `json:"url,omitempty"`
	} `json:"papers,omitempty"`
	Total int `json:"total"`
}

// PaperBase defines model for paperBase.
type PaperBase struct {
	Published string `json:"published"`
	Subject   string `json:"subject"`
	Tag       string `json:"tag"`
	Url       string `json:"url"`
}

// PaperItem defines model for paperItem.
type PaperItem struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// Author defines model for author.
type Author = string

// MaxResult defines model for max_result.
type MaxResult = int

// PaperId defines model for paper-id.
type PaperId = string

// Title defines model for title.
type Title = string

// InternalServerError エラー表現として、 [Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) を用いる。
// API クライアントでのエラーハンドリングの実装時は、 `type` を利用する。
// リソース個別のエラー表現は、各API仕様に記載する。
type InternalServerError = ProblemDetail

// NotFound エラー表現として、 [Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) を用いる。
// API クライアントでのエラーハンドリングの実装時は、 `type` を利用する。
// リソース個別のエラー表現は、各API仕様に記載する。
type NotFound = ProblemDetail

// SearchGetParams defines parameters for SearchGet.
type SearchGetParams struct {
	Title     Title      `form:"title" json:"title"`
	Author    *Author    `form:"author,omitempty" json:"author,omitempty"`
	MaxResult *MaxResult `form:"max_result,omitempty" json:"max_result,omitempty"`
}

// PapersPostJSONRequestBody defines body for PapersPost for application/json ContentType.
type PapersPostJSONRequestBody = PaperCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /health)
	HealthGet(w http.ResponseWriter, r *http.Request)
	// 論文削除
	// (DELETE /paper/{paper-id})
	PaperDelete(w http.ResponseWriter, r *http.Request, paperId PaperId)
	// 論文詳細取得
	// (GET /paper/{paper-id})
	PaperGet(w http.ResponseWriter, r *http.Request, paperId PaperId)
	// 論文一覧取得
	// (GET /papers)
	PapersGet(w http.ResponseWriter, r *http.Request)
	// 論文登録
	// (POST /papers)
	PapersPost(w http.ResponseWriter, r *http.Request)
	// 論文検索
	// (GET /search)
	SearchGet(w http.ResponseWriter, r *http.Request, params SearchGetParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ヘルスチェック
// (GET /health)
func (_ Unimplemented) HealthGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 論文削除
// (DELETE /paper/{paper-id})
func (_ Unimplemented) PaperDelete(w http.ResponseWriter, r *http.Request, paperId PaperId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 論文詳細取得
// (GET /paper/{paper-id})
func (_ Unimplemented) PaperGet(w http.ResponseWriter, r *http.Request, paperId PaperId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 論文一覧取得
// (GET /papers)
func (_ Unimplemented) PapersGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 論文登録
// (POST /papers)
func (_ Unimplemented) PapersPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 論文検索
// (GET /search)
func (_ Unimplemented) SearchGet(w http.ResponseWriter, r *http.Request, params SearchGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthGet operation middleware
func (siw *ServerInterfaceWrapper) HealthGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PaperDelete operation middleware
func (siw *ServerInterfaceWrapper) PaperDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "paper-id" -------------
	var paperId PaperId

	err = runtime.BindStyledParameterWithLocation("simple", false, "paper-id", runtime.ParamLocationPath, chi.URLParam(r, "paper-id"), &paperId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paper-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PaperDelete(w, r, paperId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PaperGet operation middleware
func (siw *ServerInterfaceWrapper) PaperGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "paper-id" -------------
	var paperId PaperId

	err = runtime.BindStyledParameterWithLocation("simple", false, "paper-id", runtime.ParamLocationPath, chi.URLParam(r, "paper-id"), &paperId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paper-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PaperGet(w, r, paperId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PapersGet operation middleware
func (siw *ServerInterfaceWrapper) PapersGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PapersGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PapersPost operation middleware
func (siw *ServerInterfaceWrapper) PapersPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PapersPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SearchGet operation middleware
func (siw *ServerInterfaceWrapper) SearchGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchGetParams

	// ------------- Required query parameter "title" -------------

	if paramValue := r.URL.Query().Get("title"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "title"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "title", r.URL.Query(), &params.Title)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	// ------------- Optional query parameter "max_result" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_result", r.URL.Query(), &params.MaxResult)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_result", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthGet)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/paper/{paper-id}", wrapper.PaperDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/paper/{paper-id}", wrapper.PaperGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/papers", wrapper.PapersGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/papers", wrapper.PapersPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchGet)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbU8byR3/KqtJX9ypCzbXVFf5HZdce64uF5SHV6nFDfYY7916Z29mnIKQJe8ux8OF",
	"FIQSAhENJCVAIDJJSVTyyIcZ/JBvUc3M2l7baxtSkr7hjbXemfk//ub3n/nvBEjirI0tZDEKYhPAhgRm",
	"EUNE/oM5lsFEPBkWiIFfcoiMAx1YMItArDaqA5rMoCwU09i4LUYoI4Y1CvJ5HWTh2DBBNGeyTmICM4Ki",
	"UigN5aqBqF6Ta1gMjSIiBdvQRqTPSNXF2pBlGlLrwzog6JecQVAKxBjJoe7mMoOZqJOlavAkAvNiMrWx",
	"RZEMaNxiiFjQvIrITUS+JURFN4kthiwZIWjbppGEzMBWxCZ4xETZ3/9EsSXGGnp+R1AaxMC5SCN7ETVK",
	"I0Nq1UXEoGEqG1KIJolhC6EgBrj7kntvubcgfp3i0cHt8vI/uLPD3W3uPVEvS+svSgszQAcZBFM+GgaT",
	"SURp3wVsMYLNvkHTxH/vu0BQClnMgCZtNtEPxQjGJoKWDG6ogO8aCrolJnTtJcQyOPVxay8TY9Swui8V",
	"i3/A7M84Z6U+f57Kc9Ol4n3u3OXuHHfW4he5s1vae186XOXOCndvcW+Hu+9EvtxX3JkTGXQmzxKnEpev",
	"bUupZEiwwQWCIJObG5rm5TSI3eieIEkh30CKQF6fADbBNiLMUBtZ8U6L2gB9tPvSII0bQNKSmpuokxse",
	"+QklGcgn6mJAdXepvDRd9n4trT+vHr4r/bYO2qbryrm/IHY6niVllFLDkIV6eELHdZCzU53ldY6LHjSk",
	"ScrxI/Zkv/LiWWl+qfT+Xse4fW9QaVhzEDKQDltojIXtB7/0KBgwlKW9NrqcHmcoKwOlpEFC4Lj8jxk0",
	"A2qCJS4YGjVPb1jWwemjg0J1c6uL002sI+tsc23wa0D14XZl/j13trlzjzubvOBoN/y1mlpMtTQm2nfX",
	"rg1pg0Nxmvgiw5hNY5EIw9ik/QZi6X5MRiMZljUjJJ38+k/Rr7/UuLtYubPNnUlBYAX3b9bgUFzj7p7Q",
	"6m5w9xH39rk3w50t7hQbFcmbl+9nBed5+9x9JmpUca36r1/LKy539oR9PwpnfxQaSjNPpJKVmpIgVZYK",
	"t0ozj4PSa74KKaWFycGh+NGbu+WtZe7sVreXq29nA5KA3gKVVIdI1tVotbBxd7G681TWWkXfi9x7LJ17",
	"IJ3bkc8F7i1xb5c7O+Wl6cruutT6oXC/dHDAC05L7a67UF6aFuIP7wjZvp1tWxGJ88ZwEqdQu7nXBJY0",
	"KfIV927LUO1x97mKmR+hgvvtGEMWNbClXULZEUT6w/QYFmXQSqIu8KqsvK7cWasUp8uzBQGJjdfcWdGu",
	"X4lrSpX2hUzZnlggDJoRWZ3erCxMSTyuSUEKEP8UuPFBU7x+Jf4l0EEak6wgHJAjRpiFlEGWo+32STRL",
	"hVPS8UPx7O7LkM+C9nNogPiaBdVz7hTruJTV+5i5V0ApL02HWa9edFFZ2S4K7LmLRweF8uS8wLEPcaH8",
	"+pV4zxC1so8YrYetwdE++AMpb0JZgKNaueOvVy//EMZPVxEkyYyk5nZaDiHe5gldyhAxu574ayS6sVp5",
	"8ajycqH8YFWRqKAkAbAp7oVW3/+N0BPhBoQpahTt9rjkRkyDZlB4baY5JSO0bsPRk4Ur6EJNsBKjFukB",
	"Y9qcK629Lq8+VYWqo4uyUsY+6YGrR93snvK8ZLg0bt+BSl6l+FDQlPufGo+sg4ZKG9pjxk2gg5uIULUq",
	"2h/tjwpfsI0saBsgBv7QH+0fEKGELCO9j2QQNFlGPI6qg16z5nPntPKmW910RKlbFhQidDvc3eKex909",
	"WQ9EOOWFJZ4SVCclimNjyx31q2i0XQH++exKIbdSNgvJuKhkYWFWO4EKxIWPJ4QQdSCMTNRaFHkVbhMx",
	"1DWzCl7i4DP724eVDVHvH85xZyokuZI/LyqRelNTp8PNoDElUu+ciHN1CzLOtxtoYa12LT7rFoDzKkRh",
	"Ia6HMlJvKeR18Ee127ovCGsbNcPR51cJjAAK1WuQyOs9eaOOruC1qSfGFH+cHsCiXdosJ2yv1MwL6ayc",
	"sdn/H6utt/NWxNaJkh6n6tXR21zHe6CXdi5/p4dB2WE4A2EHEJ4qplqbH+0saGN6TCBVVt58mPt3bwgN",
	"CYnqtIko+wanxk8XPn7XMt/+MeGr6EC7K37X7AxapwwtBYdOREXlrfVERKUuet3wpa7CH1Nh1W0jr/ec",
	"6H/CO8bMwFe6T1q2g/f/M9L8HMhudBx8ZPsvEurGI1cr1DWn4nuchKZ2CSd/1pQKvwMQAxnG7FgkYooJ",
	"GUxZbMLGhOXFrRcSA46YftcCE9b0pRecjw5EhYuJ/H8DAAD//yXA0taYHgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
